### ISSUE TITLE
CSS Selector within inline styles

### ISSUE THREAD

**Issue by marcustut** [maxence-charriere/go-app#521]
I'm not sure whether this is possible but if this is possible then it will be really great.
I wanted to implement a CSS style for an `input` element as following

```css
::placeholder {
  color: red;
}
```

how would I do this using the `.Style()` function provided?
